import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';
import chalk from 'chalk';
import type { Framework, PackageManager } from './detect.js';
import { getInstallCommand } from './detect.js';

/** Options for the scaffold operation. */
export interface ScaffoldOptions {
  cwd: string;
  framework: Framework;
  pm: PackageManager;
  extras: ('docker' | 'k8s')[];
  installCli: boolean;
  skipInstall: boolean;
  dryRun: boolean;
}

/** Track what was done for the summary. */
export interface ScaffoldResult {
  packagesInstalled: string[];
  filesCreated: string[];
  filesModified: string[];
  scriptsAdded: string[];
}

/**
 * Determine which @stacklance/envguard-* packages to install.
 */
function getPackages(framework: Framework, extras: string[], installCli: boolean): string[] {
  const packages = ['@stacklance/envguard-core', 'zod'];

  if (framework === 'nestjs') {
    packages.push('@stacklance/envguard-nestjs');
  }

  if (extras.includes('docker')) {
    packages.push('@stacklance/envguard-docker');
  }

  if (extras.includes('k8s')) {
    packages.push('@stacklance/envguard-k8s');
  }

  if (installCli) {
    packages.push('@stacklance/envguard-cli');
  }

  return packages;
}

/**
 * Generate an env.schema.ts with sensible defaults for the framework.
 */
function generateSchemaContent(framework: Framework): string {
  const lines = [
    "// Auto-generated by create-envguard",
    "// Review and adjust types as needed",
    "",
    "import { z } from 'zod'",
    "import { guard } from '@stacklance/envguard-core'",
    "",
    "export const env = guard({",
  ];

  switch (framework) {
    case 'next':
      lines.push(
        "  NODE_ENV: z.enum(['development', 'staging', 'production']),",
        "  NEXT_PUBLIC_API_URL: z.string().url().optional(),",
        "  DATABASE_URL: z.string().url().optional(),",
      );
      break;
    case 'nestjs':
      lines.push(
        "  NODE_ENV: z.enum(['development', 'staging', 'production']),",
        "  PORT: z.coerce.number().default(3000),",
        "  DATABASE_URL: z.string().url(),",
      );
      break;
    case 'vite':
      lines.push(
        "  NODE_ENV: z.enum(['development', 'staging', 'production']),",
        "  VITE_API_URL: z.string().url().optional(),",
      );
      break;
    case 'express':
      lines.push(
        "  NODE_ENV: z.enum(['development', 'staging', 'production']),",
        "  PORT: z.coerce.number().default(3000),",
        "  DATABASE_URL: z.string().url().optional(),",
      );
      break;
    default:
      lines.push(
        "  NODE_ENV: z.enum(['development', 'staging', 'production']),",
        "  PORT: z.coerce.number().default(3000),",
      );
  }

  lines.push("})", "");
  return lines.join('\n');
}

/**
 * Create .env.example from .env by stripping values.
 */
function createEnvExample(cwd: string): string[] {
  const envPath = join(cwd, '.env');
  const examplePath = join(cwd, '.env.example');
  const created: string[] = [];

  if (existsSync(envPath)) {
    const content = readFileSync(envPath, 'utf-8');
    const stripped = content
      .split('\n')
      .map((line) => {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) return line;
        const eqIdx = trimmed.indexOf('=');
        if (eqIdx > 0) return trimmed.slice(0, eqIdx + 1);
        return line;
      })
      .join('\n');

    writeFileSync(examplePath, stripped, 'utf-8');
    created.push('.env.example');
  }

  return created;
}

/**
 * Ensure .env is in .gitignore.
 */
function ensureGitignore(cwd: string): boolean {
  const gitignorePath = join(cwd, '.gitignore');
  let content = '';

  if (existsSync(gitignorePath)) {
    content = readFileSync(gitignorePath, 'utf-8');
    if (content.split('\n').some((l) => l.trim() === '.env')) {
      return false;
    }
  }

  const newline = content.length > 0 && !content.endsWith('\n') ? '\n' : '';
  writeFileSync(gitignorePath, content + newline + '.env\n', 'utf-8');
  return true;
}

/**
 * Add envguard scripts to package.json.
 */
function addScripts(cwd: string): string[] {
  const pkgPath = join(cwd, 'package.json');
  if (!existsSync(pkgPath)) return [];

  const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
  pkg.scripts = pkg.scripts ?? {};

  const added: string[] = [];

  if (!pkg.scripts['env:check']) {
    pkg.scripts['env:check'] = 'env-guard check';
    added.push('env:check');
  }

  if (!pkg.scripts['predev']) {
    pkg.scripts['predev'] = 'env-guard check';
    added.push('predev');
  }

  if (!pkg.scripts['prebuild']) {
    pkg.scripts['prebuild'] = 'env-guard check';
    added.push('prebuild');
  }

  if (added.length > 0) {
    writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf-8');
  }

  return added;
}

/**
 * Execute the full scaffold operation.
 */
export function scaffold(options: ScaffoldOptions): ScaffoldResult {
  const { cwd, framework, pm, extras, installCli, skipInstall, dryRun } = options;

  const result: ScaffoldResult = {
    packagesInstalled: [],
    filesCreated: [],
    filesModified: [],
    scriptsAdded: [],
  };

  const packages = getPackages(framework, extras, installCli);
  result.packagesInstalled = packages;

  if (dryRun) {
    // Simulate without writing
    result.filesCreated.push('env.schema.ts');
    if (existsSync(join(cwd, '.env'))) {
      result.filesCreated.push('.env.example');
    }
    result.filesModified.push('.gitignore');
    result.scriptsAdded.push('env:check', 'predev', 'prebuild');
    return result;
  }

  // 1. Install packages
  if (!skipInstall) {
    const cmd = getInstallCommand(pm, packages);
    console.log(chalk.gray(`  $ ${cmd}`));
    try {
      execSync(cmd, { cwd, stdio: 'pipe' });
    } catch {
      console.warn(chalk.yellow('  ⚠ Package install failed. You may need to install manually.'));
    }
  }

  // 2. Create env.schema.ts
  const schemaPath = join(cwd, 'env.schema.ts');
  if (!existsSync(schemaPath)) {
    writeFileSync(schemaPath, generateSchemaContent(framework), 'utf-8');
    result.filesCreated.push('env.schema.ts');
  }

  // 3. Create .env.example
  const exampleFiles = createEnvExample(cwd);
  result.filesCreated.push(...exampleFiles);

  // 4. Ensure .gitignore has .env
  if (ensureGitignore(cwd)) {
    result.filesModified.push('.gitignore');
  }

  // 5. Add scripts to package.json
  if (installCli) {
    const scripts = addScripts(cwd);
    result.scriptsAdded = scripts;
    if (scripts.length > 0) {
      result.filesModified.push('package.json');
    }
  }

  return result;
}

/**
 * Print a summary of what was done.
 */
export function printSummary(result: ScaffoldResult): void {
  console.log('');
  console.log(chalk.bold.green('✔ envguard setup complete!\n'));

  if (result.packagesInstalled.length > 0) {
    console.log(chalk.bold('  Packages:'));
    for (const pkg of result.packagesInstalled) {
      console.log(`    ${chalk.cyan('+')} ${pkg}`);
    }
  }

  if (result.filesCreated.length > 0) {
    console.log(chalk.bold('\n  Created:'));
    for (const file of result.filesCreated) {
      console.log(`    ${chalk.green('+')} ${file}`);
    }
  }

  if (result.filesModified.length > 0) {
    console.log(chalk.bold('\n  Modified:'));
    for (const file of result.filesModified) {
      console.log(`    ${chalk.yellow('~')} ${file}`);
    }
  }

  if (result.scriptsAdded.length > 0) {
    console.log(chalk.bold('\n  Scripts added:'));
    for (const script of result.scriptsAdded) {
      console.log(`    ${chalk.cyan('+')} ${script}`);
    }
  }

  console.log('');
}
